spring.application.name=ecomProj

#spring.datasource.url=jdbc:h2:mem:shrutidb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.defer-datasource-initialization=true

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=_Shruti_12
spring.datasource.driver_class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-Sql=true
spring.datasource.hiraki.auto-commit=false
